CREATE CONSTRAINT node_agent_name IF NOT EXISTS FOR (n:Agent) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_hub_name IF NOT EXISTS FOR (n:Hub) REQUIRE n.name IS UNIQUE;
MERGE (n:Agent {name: 'code-reviewer'}) SET n.role = 'review', n.description = 'Revisa um diff ou PR em busca de bugs, riscos de segurança, aderência ao DESIGN/convenções e simplificações. Use ao final de um /build, antes de abrir PR, ou quando o usuário pedir revisão. Read-only — não altera código.';
MERGE (n:Agent {name: 'debugger'}) SET n.role = 'debug', n.description = 'Investiga falha, stacktrace ou teste intermitente, isola a causa-raiz e propõe o fix mínimo. Use quando algo quebra ou um teste falha sem causa óbvia. Roda comandos para reproduzir.';
MERGE (n:Agent {name: 'documenter'}) SET n.role = 'documentation', n.description = 'Expert em documentação humano×LLM que NÃO entra na KB — doc de código/módulos, ADR, runbook/onboarding, referência/notas. Use ao registrar o que mudou/aconteceu ou documentar como algo funciona. Escreve em docs/.';
MERGE (n:Agent {name: 'explorer'}) SET n.role = 'search', n.description = 'Explora uma codebase desconhecida e devolve um mapa conciso (onde está cada coisa, como se conecta) sem despejar arquivos inteiros. Use para localizar código, entender arquitetura ou responder "onde fica X" antes de implementar. Read-only.';
MERGE (n:Agent {name: 'external-observer'}) SET n.role = 'observation', n.description = 'Observa um alvo externo/opaco (site, API, app rodando) via MCPs e docs, infere a lógica e a confronta com uma referência (contrato, spec, sua implementação). Use para validar comportamento de runtime contra referência ou mapear um produto que você não tem o fonte. Read-only/outward — só observa, nunca replica nem aplica.';
MERGE (n:Agent {name: 'git-workflow'}) SET n.role = 'vcs', n.description = 'Expert em higiene de repositório e fluxo Git/PR — estrutura, conventional commits, branches, pull requests, .gitignore. Use ao preparar commits/PRs, revisar histórico ou organizar o repo. Roda git/gh.';
MERGE (n:Agent {name: 'security-reviewer'}) SET n.role = 'security', n.description = 'Revisão de segurança dedicada e em profundidade — segredos, injeção, authn/authz, dependências/supply-chain, config insegura. Use quando a mudança toca superfície sensível ou sob pedido. Read-only.';
MERGE (n:Agent {name: 'test-writer'}) SET n.role = 'testing', n.description = 'Gera ou completa testes para um alvo (função, módulo, feature), cobrindo caminho feliz, edge cases e os Acceptance Tests do DEFINE. Use durante /build ou quando faltar cobertura. Pode criar/editar arquivos de teste e rodá-los.';
MERGE (n:Agent {name: 'validator'}) SET n.role = 'validation', n.description = 'Verifica se o resultado entregue cumpre a spec e os Acceptance Tests do DEFINE — roda e observa o comportamento. Use ao fim de um /build ou antes do /ship para confirmar conformidade. Roda checagens.';
MERGE (n:Hub {name: 'max'}) SET n.role = 'orchestrator-hub', n.description = 'Modo MAX — hub orquestrador-mestre do grafo de agentes (H7)';
MATCH (a {name: 'code-reviewer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'code-reviewer'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'documenter'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'git-workflow'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'max'}), (b {name: 'code-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'debugger'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'documenter'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'explorer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'external-observer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'git-workflow'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'security-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'test-writer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'validator'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'security-reviewer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'test-writer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'validator'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);