CREATE (:Agent {name: 'code-reviewer', role: 'review', description: 'Revisa um diff ou PR em busca de bugs, riscos de segurança, aderência ao DESIGN/convenções e simplificações. Use ao final de um /build, antes de abrir PR, ou quando o usuário pedir revisão. Read-only — não altera código.'});
CREATE (:Agent {name: 'debugger', role: 'debug', description: 'Investiga falha, stacktrace ou teste intermitente, isola a causa-raiz e propõe o fix mínimo. Use quando algo quebra ou um teste falha sem causa óbvia. Roda comandos para reproduzir.'});
CREATE (:Agent {name: 'documenter', role: 'documentation', description: 'Expert em documentação humano×LLM que NÃO entra na KB — doc de código/módulos, ADR, runbook/onboarding, referência/notas. Use ao registrar o que mudou/aconteceu ou documentar como algo funciona. Escreve em docs/.'});
CREATE (:Agent {name: 'explorer', role: 'search', description: 'Explora uma codebase desconhecida e devolve um mapa conciso (onde está cada coisa, como se conecta) sem despejar arquivos inteiros. Use para localizar código, entender arquitetura ou responder "onde fica X" antes de implementar. Read-only.'});
CREATE (:Agent {name: 'git-workflow', role: 'vcs', description: 'Expert em higiene de repositório e fluxo Git/PR — estrutura, conventional commits, branches, pull requests, .gitignore. Use ao preparar commits/PRs, revisar histórico ou organizar o repo. Roda git/gh.'});
CREATE (:Agent {name: 'security-reviewer', role: 'security', description: 'Revisão de segurança dedicada e em profundidade — segredos, injeção, authn/authz, dependências/supply-chain, config insegura. Use quando a mudança toca superfície sensível ou sob pedido. Read-only.'});
CREATE (:Agent {name: 'test-writer', role: 'testing', description: 'Gera ou completa testes para um alvo (função, módulo, feature), cobrindo caminho feliz, edge cases e os Acceptance Tests do DEFINE. Use durante /build ou quando faltar cobertura. Pode criar/editar arquivos de teste e rodá-los.'});
CREATE (:Agent {name: 'validator', role: 'validation', description: 'Verifica se o resultado entregue cumpre a spec e os Acceptance Tests do DEFINE — roda e observa o comportamento. Use ao fim de um /build ou antes do /ship para confirmar conformidade. Roda checagens.'});
MATCH (a:Agent {name: 'code-reviewer'}), (b:Agent {name: 'security-reviewer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'code-reviewer'}), (b:Agent {name: 'test-writer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'debugger'}), (b:Agent {name: 'explorer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'debugger'}), (b:Agent {name: 'test-writer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'documenter'}), (b:Agent {name: 'explorer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'explorer'}), (b:Agent {name: 'code-reviewer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'explorer'}), (b:Agent {name: 'debugger'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'git-workflow'}), (b:Agent {name: 'code-reviewer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'security-reviewer'}), (b:Agent {name: 'code-reviewer'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'test-writer'}), (b:Agent {name: 'validator'}) CREATE (a)-[:CONNECTS_TO]->(b);
MATCH (a:Agent {name: 'validator'}), (b:Agent {name: 'test-writer'}) CREATE (a)-[:CONNECTS_TO]->(b);